# development playbook
# - hosts: all
#   remote_user: ubuntu
#   become: true
#   roles:
#     - { role: common,               tags: [ 'common'   ] }

- hosts: all

  roles:
  - provision_local

- hosts: ckan
  roles:
  - common
  - ckan
  # - solr