# Handler for common commands
- name: Restart Apache
  become: true
  service: 
    name: apache2 
    state: restarted

- name: Restart Nginx
  become: true
  service: 
    name: nginx
    state: restarted

- name: Start Jetty
  service: 
    name: jetty
    state: started

- name: Restart Jetty
  service: 
    name: jetty
    state: restarted

- name: restart postgresql
  become: true
  service:
    name: "{{ postgresql_daemon }}"
    state: "restarted"
    sleep: 5