## Adopted from https://github.com/geerlingguy/ansible-role-solr/

- include: user.yml

- name: Check if Solr has been installed already.
  stat:
    path: "{{ solr_install_path }}"
  register: solr_install_path_status

- name: Download Solr.
  get_url:
    url: "{{ solr_mirror }}/lucene/solr/{{ solr_version }}/{{ solr_filename }}.tgz"
    dest: "{{ solr_workspace }}/{{ solr_filename }}.tgz"
    force: false
  when: solr_install_path_status.stat.isdir is not defined
  register: solr_download_status

- name: Expand Solr.
  unarchive:
    src: "{{ solr_workspace }}/{{ solr_filename }}.tgz"
    dest: "{{ solr_workspace }}"
    copy: false
  when: solr_download_status.changed

- include: install.yml

- name: Ensure solr is started and enabled on boot
  service:
    name: "{{ solr_service_name }}"
    state: "started"
    enabled: true

- name: disable ipv6 in redis # check https://github.com/antirez/redis/issues/5055#issuecomment-405516849
  become: true
  lineinfile:
    path: "/etc/redis/redis.conf"
    regexp: "bind .*"
    line: bind 127.0.0.1

- name: Ensure redis is started and enabled on boot
  service:
    name: "redis-server"
    state: "started"
    enabled: true


- include: configure.yml
  become: true
- include: cores.yml

- name: Apply CKAN schema factory configuration changes.
  become: true
  blockinfile:
    dest: "{{ ckan_solr_config_file }}"
    insertafter: "<config>"
    block: '<schemaFactory class="ClassicIndexSchemaFactory"/>'
    state: present
  notify: restart solr

- name: Remove update processer section
  become: true
  xml:
    path: "{{ ckan_solr_config_file }}"
    xpath: /config/updateRequestProcessorChain/processor[@class='solr.AddSchemaFieldsUpdateProcessorFactory']
    set_children: []
    state: absent
    pretty_print: yes
  notify: restart solr

- name: Remove init params processer section
  become: true
  xml:
    path: "{{ ckan_solr_config_file }}"
    xpath: /config/initparams[@path='/update/**']
    set_children: []
    state: absent
    pretty_print: yes
  notify: restart solr

- name: Remove default search field config
  become: true
  lineinfile:
    path: "{{ ckan_solr_schema_source }}"
    regexp: "defaultSearchField"
    state: absent
  notify: restart solr

- name: Remove solrQueryParser config
  become: true
  lineinfile:
    path: "{{ ckan_solr_schema_source }}"
    regexp: "solrQueryParser"
    state: absent
  notify: restart solr

- name: replace old datatypes with new ones
  become: true
  replace:
    path: "{{ ckan_solr_schema_source }}"
    regexp: "{{ item.old }}"
    replace: "{{ item.new }}"
  loop:
  - {old: "textgen", new: "text_general"}
  - {old: "tdate", new: "pdate"}
  - {old: "tdates", new: "pdates"}
  - {old: "tlong", new: "plong"}
  - {old: "tlongs", new: "tlongs"}
  - {old: "tdouble", new: "pdouble"}
  - {old: "tdoubles", new: "pdoubles"}


- name: Delete managed-schema file
  become: true
  file:
    path: "{{ ckan_solr_conf_path }}/managed-schema"
    state: absent
  notify: restart solr

- include: cleanup.yml

