- name: Ensure solr_user group exists.
  group:
    name: "{{ solr_user }}"
    state: present
  become: true

- name: Ensure solr_user exists.
  user:
    name: "{{ solr_user }}"
    group: "{{ solr_user }}"
    state: present
  become: true
